"""empty message

Revision ID: 36ecc35f52f7
Revises: 5d04d3cec2b5
Create Date: 2021-05-14 11:51:25.760874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ecc35f52f7'
down_revision = '5d04d3cec2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('last_update', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bg_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('signature', sa.String(length=500), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('subname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subname', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('signature')
        batch_op.drop_column('category_id')
        batch_op.drop_column('bg_image')

    op.drop_table('category')
    # ### end Alembic commands ###
