"""empty message

Revision ID: 4f05dc5c4d5f
Revises: 83ee0e3f7f53
Create Date: 2021-06-02 23:29:41.665172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f05dc5c4d5f'
down_revision = '83ee0e3f7f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('font_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('font_name', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('font_name')
        batch_op.drop_column('font_size')

    # ### end Alembic commands ###
