"""empty message

Revision ID: 7806c64d4f43
Revises: 
Create Date: 2021-06-03 15:07:34.759574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7806c64d4f43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('ip', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('ip', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fonts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('font_cdn', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('date_generated', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('token_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('email', sa.String(length=127), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.String(length=127), nullable=False),
    sa.Column('response_msg', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('error_code', sa.String(length=127), nullable=True),
    sa.Column('error_source', sa.String(length=127), nullable=True),
    sa.Column('txn_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('bg_image', sa.String(length=500), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('font_name', sa.String(length=250), nullable=False),
    sa.Column('certx', sa.Integer(), nullable=False),
    sa.Column('certy', sa.Integer(), nullable=False),
    sa.Column('qrx', sa.Integer(), nullable=False),
    sa.Column('qry', sa.Integer(), nullable=False),
    sa.Column('certnox', sa.Integer(), nullable=False),
    sa.Column('certnoy', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('date_generated', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('coursename', sa.String(length=500), nullable=False),
    sa.Column('last_update', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_num', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_code')
    op.drop_table('certificate')
    op.drop_table('api_key')
    op.drop_table('group')
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('token')
    op.drop_table('public_api_key')
    op.drop_table('newsletter')
    op.drop_table('fonts')
    op.drop_table('feedback')
    op.drop_table('contact')
    # ### end Alembic commands ###
