"""empty message

Revision ID: c9a0a430a7da
Revises: eabd7ab06af3
Create Date: 2021-05-14 11:18:42.535200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a0a430a7da'
down_revision = 'eabd7ab06af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_stat1')
    op.drop_table('sqlite_stat4')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('last_update',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.alter_column('last_update',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.alter_column('last_update',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('last_update',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=False)

    op.create_table('sqlite_stat4',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('neq', sa.NullType(), nullable=True),
    sa.Column('nlt', sa.NullType(), nullable=True),
    sa.Column('ndlt', sa.NullType(), nullable=True),
    sa.Column('sample', sa.NullType(), nullable=True)
    )
    op.create_table('sqlite_stat1',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('stat', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
