"""empty message

Revision ID: fd310d78e3f7
Revises: 0855df808efb
Create Date: 2021-05-24 16:58:37.016875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd310d78e3f7'
down_revision = '0855df808efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_api_key', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
